### ISSUE TITLE
Add link to Oxygen Concentrator Requirement

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#104]
Add a new button near to covid19India button

Button Text: [Oxygen Concentrator Requirements
Link: https://docs.google.com/spreadsheets/d/e/2PACX-1vS7nP0QvIvm5VDEbVDG0ELECYS446P-MgLwdX_elDrYbkN39g_o90wmJIMcazmcLH38Snn7rSqwAS_y/pubhtml?gid=972869835&single=true

**Comment by bodhish** [comment]
@abhinandanarya06 HOLD

**Comment by SaloniMehta25** [comment]
is it possible to add filters to this?

**Comment by Deep-Codes** [comment]
Yep
