### ISSUE TITLE
Medical supplies - demand/ supply

### ISSUE THREAD

**Issue by SaloniMehta25** [coronasafe/life#106]
we have currently put a public google doc where people can see the requirements (https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vS7nP0QvIvm5VDEbVDG0ELECYS446P-MgLwdX_elDrYbkN39g_o90wmJIMcazmcLH38Snn7rSqwAS_y/pubhtml?gid=972869835&single=true), we need to put a clean table directly on the website where people can filter based on various criteria (something like this: https://www.covid19india.org/)
At the backend, we will need a login which allows us to input the supply met against the demand and show residual demand 

This is the google sheet from which data is currently being picked up: https://docs.google.com/spreadsheets/d/1b9wYaz5yxiMFNSpDmi1Z3jJWT3fjx5jw2WV7clc0tYM/edit?resourcekey#gid=972869835

**Comment by bodhish** [comment]
Rework oxygen_requirment

**Comment by khavinshankar** [comment]
@bodhish 
we have something like this,
![Screenshot from 2021-04-27 09-30-15](https://user-images.githubusercontent.com/29787772/116183357-540d5100-a73b-11eb-9ff4-a63c03ecfe3b.png)
and why are we not using that, any reason ?

**can we just use the above component or does it need to be modified?**

**Comment by bodhish** [comment]
It has to modified to a tabular format

**Comment by khavinshankar** [comment]
@bodhish 
is this ok?
![image](https://user-images.githubusercontent.com/29787772/116234636-783c5280-a77a-11eb-96bd-72fa074285e3.png)


**any suggestions ?**

**Comment by khavinshankar** [comment]
@bodhish from https://docs.google.com/spreadsheets/d/1b9wYaz5yxiMFNSpDmi1Z3jJWT3fjx5jw2WV7clc0tYM/edit?resourcekey#gid=972869835, do we need to only show the dashboard sheet or all 4 sheets?

**Comment by bodhish** [comment]
Will get back on this
