### ISSUE TITLE
API link visible as a text

### ISSUE THREAD

**Issue by AmjadNoor** [coronasafe/life#107]
## Describe the bug
API link is sown as plain text in GitHub pages.

## To Reproduce
1. Go to [coronasafe Github page](https://life-api.coronasafe.network/).
2. Click on API link. API link is not clickable because they sown as a plain text.
3. See error

## Expected behavior
I want API link in Github page if anyone visit coronasafe Github page then they able to click the API link.

## Screenshots
![Screenshot_2021-04-26-13-03-47-83](https://user-images.githubusercontent.com/56997478/116046919-28ce2780-a691-11eb-83a4-7ae6e8a52fa7.jpg)
## Smartphone (please complete the following information):
- Device: [Realme C3]
- OS: [Android 10]
- Browser [Chrome]
- Version [90.0.4430.82 (Latest version)]
## Additional
I am done with this please assign it to me and i will highly appreciate you. Thanks 😊

**Comment by shrihari689** [comment]
Closed by #108
