### ISSUE TITLE
Edit feature on frontend from admins 

### ISSUE THREAD

**Issue by chicksim** [coronasafe/life#112]
Can the admin logins make edits on the frontend - at least - edit the verifier comments/description on the final card. And this edit modifies airtable database too? This can help when I am looking for something, calling a number and it did not help me, I want to update the comment, and it records the timestamp. Just show the last comment. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bodhish** [comment]
Let's not work on it. Switching away from airtable

**Comment by karmakoder** [comment]
Closing based on @bodhish's comments.
