### ISSUE TITLE
Not showing data but showing its available in state list page

### ISSUE THREAD

**Issue by abhinandanarya06** [coronasafe/life#113]
**Describe the bug**
Showing available resources (`ambulance`) but no data rendering

**To Reproduce**
1. Go to [`https://life.coronasafe.network/delhi_(nct)/south_west_delhi`](https://life.coronasafe.network/delhi_(nct)/south_west_delhi)
2. Showing available ambulance. Now, Click on [Ambulance Card](https://life.coronasafe.network/delhi_(nct)/south_west_delhi/ambulance)
3. Don't showing any data!

**Expected behavior**
Should show data of ambulance in south west delhi

**Screenshots**
![image](https://user-images.githubusercontent.com/52771399/116094040-d27adc00-a6c4-11eb-9f5d-e3570ed337ae.png)

![image](https://user-images.githubusercontent.com/52771399/116093961-be36df00-a6c4-11eb-90f5-79e65c2a38e2.png)

**Comment by peeyush14goyal** [comment]
Same is happening in some other cities too

**Comment by Deep-Codes** [comment]
<img width="450" alt="Screenshot 2021-04-26 at 7 29 44 PM" src="https://user-images.githubusercontent.com/61158210/116095146-c4798b00-a6c5-11eb-989c-7a040c0eb529.png">

In this case there's actually no data

**Comment by peeyush14goyal** [comment]
Yes but in active_district_data.json ambulance field is true

**Comment by ProCode2** [comment]
How are active districts generated?

**Comment by shrihari689** [comment]
I could see in Airtable we have 99 Ambulances, but on out json, we do have 200+ ambulance 😶
I don't understand how it happens 🤔
Meanwhile I hope we are moving from Airtable to DB 📍
#537

**Comment by vandanabhandari** [comment]
I can try to fix this

**Comment by vandanabhandari** [comment]
looks like this is fixed ..
https://life.coronasafe.network/delhi_(nct)/west_delhi. The Ambulance button is not highlighted.

**Comment by Deep-Codes** [comment]
> https://life.coronasafe.network/delhi_(nct)/west_delhi

Yeah it's fixed
