### ISSUE TITLE
New UI design for the "Partner with US" page

### ISSUE THREAD

**Issue by joelsajichacko** [coronasafe/life#127]
[Link to the frame](https://www.figma.com/file/5vTeIYUU4ikk02XaPmN4rg/Raksha-Covid?node-id=106%3A249)
![Partner with us](https://user-images.githubusercontent.com/45791338/116129587-e6840500-a6e7-11eb-9eb0-5d4e127559c3.png)

**Comment by vandanabhandari** [comment]
I could try to work on  this

**Comment by Deep-Codes** [comment]
@vandanabhandari Can I ship the navbar component?  and you work on content below it ?

**Comment by shrihari689** [comment]
Is this #125 ? 📍

**Comment by Deep-Codes** [comment]
> Is this #125 ? 📍

Looks like let's ask on group

**Comment by vandanabhandari** [comment]
ok.. let me know if #125  is being worked... it does look same.. I have not started this, so can look at something else

**Comment by ProCode2** [comment]
I am working on that
