### ISSUE TITLE
Display distance from users browser location for hospitals and medicines

### ISSUE THREAD

**Issue by vandanabhandari** [coronasafe/life#136]
**Is your feature request related to a problem? Please describe.**
For a new person in town it may not be clear which location of hospital and medical shop is closest to them.

**Describe the solution you'd like**
If there is clear address with pin code. Using google api calculate the distance between latitude and longitude of your browser location to the address displayed in hospital and medical cards.

**Describe alternatives you've considered**
One must copy the address and add in google maps in different browser tabs and check.

**Additional context**

- [x] Add a mechanism to fetch latitude/longitude based on following criteria : 
1. If address lookup works, great use that. If not, 
2. If name of resource is searchable in google and we can determine a biz address then use that. If not, 
3. Use pincode. if that is also not present then dont show anything in UI. 
We will eventually store it in back-end. This is being worked on by @rishabhrawat10

**Comment by rawris** [comment]
Hi @vandanabhandari,

Can you please assign my this(@rawris) account for this issue? I don't use the other(rishabhrawat10) GitHub account anymore.

**Comment by vandanabhandari** [comment]
@karmakoder I unassigned myself. you can assign to @rawris . Thank you Rishab bhai.

**Comment by karmakoder** [comment]
> @karmakoder I unassigned myself. you can assign to @rawris . Thank you Rishab bhai.

Done. @shubhabrataroy plz try and co-ordinate with @rishabhrawat10 slack : https://app.slack.com/client/TC99SV7B6/D01VDBZK90W/user_profile/U020316AYQ5 if u can contribute some code for this geolocation utility in general.

**Comment by shrihari689** [comment]
Is this releated to 
https://github.com/coronasafe/life/issues/157
🤔

**Comment by rakeshgunduka** [comment]
@karmakoder I can take up this, as I have implemented distance calculation based on lat/ long values on Map Marker. I can have same for the card as well.

**Comment by karmakoder** [comment]
> @karmakoder I can take up this, as I have implemented distance calculation based on lat/ long values on Map Marker. I can have same for the card as well.

assigned. lets get cracking.
