### ISSUE TITLE
Unresponsive status in helpline.json

### ISSUE THREAD

**Issue by shubham2924** [coronasafe/life#141]
**Describe the bug**
"Unresponsive" verification status in helpline.json is what the bug is.

**Expected behavior**
Please put valid contact details which means they're verified properly contacted whether they're responsive or not before hand.

**Comment by vjFaLk** [comment]
@karmakoder This is more of a data entry issue, don't think it belongs here.

**Comment by karmakoder** [comment]
These issues with data are being handled in back-end for v2 api and v2 version of data with some automation. Closing this for now.
