### ISSUE TITLE
Change campaigns button name to "Donate"

### ISSUE THREAD

**Issue by khuze** [coronasafe/life#153]
Campaigns as the button name is ambiguous, can we rename it to "Donate now". A clearer CTA will help the cause. 

https://drive.google.com/file/d/1_HUus3UlJTew34vHkdF2FVDGbtfm-lxn/view

**Comment by bodhish** [comment]
Don't change the endpoint as people are sharing the url

**Comment by Deep-Codes** [comment]
Added ✅
