### ISSUE TITLE
Align breadcrumbs to the left

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#16]
Kepp the breadcrumbs on the left side for all pages. 

![image](https://user-images.githubusercontent.com/14979190/115823405-efdd4b00-a423-11eb-97d4-c0cdc0283154.png)

**Comment by shrihari689** [comment]
Fixed in  e312530c255c5d255041b1dee66bfe6360bc2e19 596fb0395fe2a068acc48e79bf5f5213f7cbbc6b 445cdae18fb1879c2b87b30901d22d4373fa3322 22ef6deb3db5f8f8c3446639f9240cdd638c6787  📍
