### ISSUE TITLE
Oxygen availability 

### ISSUE THREAD

**Issue by shubhabrataroy** [coronasafe/life#169]
**Is your feature request related to a problem? Please describe.**
Currently the app does not have any availability feature, where the suppliers can update how much oxygen they do have or if they don't have anything.

**Describe the solution you'd like**
Let the suppliers update the availability of oxygen

**Describe alternatives you've considered**
Additionally can we also add reserve features
**Additional context**

**Comment by karmakoder** [comment]
@shubhabrataroy is it duplicate of https://github.com/coronasafe/life/issues/239? If so, plz close it.

**Comment by shubhabrataroy** [comment]
Great ... yes it is fine. Closing now.
