### ISSUE TITLE
Add location based features

### ISSUE THREAD

**Issue by shubhabrataroy** [coronasafe/life#170]
Help finding resource based on users location. Example: If I keep my location turned on it would show my nearby facilities.

**Comment by Deep-Codes** [comment]
> Help finding resource based on users location. Example: If I keep my location turned on it would show my nearby facilities.

Duplicate of #157 ?

**Comment by shubhabrataroy** [comment]
> > Help finding resource based on users location. Example: If I keep my location turned on it would show my nearby facilities.
> 
> Duplicate of #157 ?

Not fully, but yes they have some similarity. Geolocation + search based on geolocation.

**Comment by vandanabhandari** [comment]
looks like a lot of usage to geolocation integration. I was looking at a similar one but have not started. https://github.com/coronasafe/life/issues/136

**Comment by karmakoder** [comment]
> @karmakoder @shubhabrataroy I think this should be combined with #157 and #136, they're similar enough I think.

Agreed. @shubhabrataroy lets plz combine efforts under https://github.com/coronasafe/life/issues/136. I'll intro u to the dev who is working on part of this problem.
