### ISSUE TITLE
Make Twitter results easier to use and more obvious 

### ISSUE THREAD

**Issue by viksit** [coronasafe/life#175]
@bodhi @Deepankar Bhade @Pradipta Ghoshal Deepankar and I just talked about adding something to the life search ui that informs people that they can do a live twitter search from there itself.

right now no one knows its there

so lets do something to make it obvious to people that this functionality exists and can be used

I proposed a) keeping the twitter div always open and b) having a message that says something like “start typing to see twitter results”

maybe to the right of the search box.

**Comment by karmakoder** [comment]
@viksit @Deep-Codes @ProCode2 can we close this now that we have a new ui for twitter serach. i think it makes it vry apparent.
