### ISSUE TITLE
Create a new resource card. 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#176]
Since we are merging to an unified schema for all resources type it would great if we could create a card component that could render those values well.

The shape of the schema can be accessed from the wiki.
Sample data is avilable at data/oxygen_v2.json

The design should also account for a upvote down vote buttons 😅

**Comment by shrihari689** [comment]
Almost completed as a part of #151 📍

**Comment by Deep-Codes** [comment]
Done!
