### ISSUE TITLE
Create a data page 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#19]
Create a new page /data and add the following 

What to do if you have verified data and want to add to the database?

Fill information these forms based on resource type if you have less than 10 contacts.

 Oxygen - https://airtable.com/shrjYwvwPhPY6h6Hw 
 Ambulance - https://airtable.com/shrAO7oA9qwh1OABJ
 Hospital - https://airtable.com/shrfZV2enmY9wge0F
 Helpline - https://airtable.com/shruCmaVNNXt1q1Uj
 Plasma  https://airtable.com/shrtvIFkPjcUxRd1H
 Medicine/Injection/Chemist - https://airtable.com/shrCNfkEdSTxeWAGg
 Doctor/Telemedicine/Consultation - https://airtable.com/shrg0KEI0qRfLRPRP
 Support groups (whatsapp, telegram, twitter, instagram) https://airtable.com/shrf64QSuwSrzWPxo
 Apply as volunteer https://airtable.com/shrDiUIg7e1IWj6mz
 Government contact https://airtable.com/shr5IdHRDcFrOKLcg

**Comment by shrihari689** [comment]
📌

![image](https://user-images.githubusercontent.com/57325503/115832732-dbec1600-a430-11eb-8ba6-60f1d841e7f2.png)

**Comment by shrihari689** [comment]
Closing this as of c8b4c15 📍
