### ISSUE TITLE
Sticky Footer overlapping other elements

### ISSUE THREAD

**Issue by samanyougarg** [coronasafe/life#195]
**Describe the bug**
The sticky footer seems to be overlapping other elements like recent tweets and resources list.

**To Reproduce**
View the Twitter results for any state/district/resource. For example, https://liferesources.in/delhi_(nct)/south_delhi/oxygen

**Expected behavior**
Footer should be fixed to the bottom and shouldn't mess with other elements on the page.

**Screenshots**
<img width="1792" alt="Screenshot 2021-04-29 at 2 43 38 PM" src="https://user-images.githubusercontent.com/32533774/116560815-a4caa880-a8f9-11eb-9fbc-1a7e98985a7b.png">

**Desktop (please complete the following information):**
- OS: MacOS
- Browser: Chrome

**Comment by Deep-Codes** [comment]
@Sandra3657 should i push the fix?

**Comment by Deep-Codes** [comment]
Fixed via 6d98f82
