### ISSUE TITLE
Update "Oxygen Concentration Requirements" link

### ISSUE THREAD

**Issue by khuze** [coronasafe/life#197]
View Screenshot - https://drive.google.com/file/d/1Dg4fmK6f4Oat18s-HlLvPAmoWM7amU-V/view?usp=drivesdk

Please update the link to the new dashboard : 
https://charts.mongodb.com/charts-swasth-deman-data-aobsf/public/dashboards/608a951e-5a65-4419-843d-d193674b3673

**Comment by Deep-Codes** [comment]
Completed by @shrihari689
