### ISSUE TITLE
Add a label source for source link

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#20]
Add a label `source` for source links. It will be super helpful for normal users to figure out 

![Screenshot_20210423-134836__01__01](https://user-images.githubusercontent.com/14979190/115841812-ce3b8e00-a43a-11eb-995e-a4fac399801a.jpg)

**Comment by peeyush14goyal** [comment]
@bodhish  There are two fields Source and Source Link in some files so added Source Link. 
Made the changes and are in Pull Request #22

**Comment by bodhish** [comment]
Looks good @peeyush14goyal
