### ISSUE TITLE
Add share to social links

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#21]
It would be super helpful if users could share the links to social media apps in a click.

**Comment by ProCode2** [comment]
@Deep-Codes done with this one?

**Comment by Deep-Codes** [comment]
Starting it now

**Comment by Deep-Codes** [comment]
Shareable Links Added: 

- [x] Twitter
- [x] LinkedIN
- [x] Facebook
- [ ] Copy to Clipboard

**Comment by Deep-Codes** [comment]
Try this way instead: https://github.com/covid19india/covid19india-react/pull/2412/

**Comment by ProCode2** [comment]
Taking up `copy to clipboard`
