### ISSUE TITLE
Create a CSV of all master data

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#210]
**Is your feature request related to a problem? Please describe.**
Many apps and front-ends written by volunteers outside of Life ecosystem use CSV as input and may not port easily to our JSON APIs.

**Describe the solution you'd like**
1. Create and host a CSV for all resources. Another CSV for oxygen, hospital etc.
2. Document the URLs in README

**Describe alternatives you've considered**
Requesting many of these developers to transform data from JSON is the only other option

**Additional context**
We want to scale up our efforts to provide a great source of data to all front-ends.

**Comment by karmakoder** [comment]
https://apipheny.io/ can be used to do this.

**Comment by jitendraag** [comment]
Ruchika is looking this. Assigning to myself.

**Comment by karmakoder** [comment]
> Ruchika is looking this. Can someone assign to me please?

done.

**Comment by technoknol** [comment]
@jitendraag what about GraphQL open endpoint ? Do we really need to transform our data according to adopter's needs? GraphQL endpoint would be good to extract data in any form they want.

**Comment by vigneshhari** [comment]
Closing this issue since we already have built the CSV auto exports. @jitendraag the file names are the same, change the extension from .json to .csv to get the csv dump.
