### ISSUE TITLE
Start writing master data to a write-only Google sheet

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#211]
**Is your feature request related to a problem? Please describe.**
We have created a good interface for programmers with our JSONs. We are trying to decentralise verification at the same time. Unfortunately, many of these volunteers don't understand JSON. It's imperative that we share master data with these volunteers using a Google sheet.

**Describe the solution you'd like**
1. Create a Google sheet that's publicly shared with everyone and is part of our documentation.
2. Start synchronising all master data on this sheet for manual volunteers outside of Life network to use.

**Describe alternatives you've considered**
We can provide a link to CSV. But that's not as intuitive as Google sheets IMHO.

**Additional context**
Now that we are a common backend and verification process in place; we are confident that the volume and quality of data in our data source is great.

This is a step to make our data more useful for non-developers.

**Comment by shrihari689** [comment]
This means we maintain a master Google Sheet where all our (JSON) data gets sync 📍 
and the sheet will be available to public as "Published Sheet" or "View Only Sheet" - Can do this ✅
Did I understood the issue correctly? 🧐

**Comment by bodhish** [comment]
Published Sheet

**Comment by technoknol** [comment]
What would be the primary use for volunteers outside of Life's network ? 

1. If they are just going to verify data, they can use https://life.coronasafe.network/ that's why the website is there as a nice presentation layer. 
2. If they are going to use those CSV to create another resource app then rather than CSV I'd rather prefer GraphQL open endpoint. Community has widely accepted GraphQL and users can shape responses in any shape they want. 

Correct me if there's 3rd use case.

**Comment by shrihari689** [comment]
@technoknol 
Yeah! that would be great use case 📍
But @jitendraag is mentioning about giving out the data for Non-Developers 📌

**Comment by shrihari689** [comment]
Issue work paused for CSV Dumps Action Deployment  📌
Note: It's also related to https://github.com/coronasafe/life/issues/210 🎉

**Comment by vigneshhari** [comment]
since we are already doing a CSV dump, if someone can figure out how to import a csv into google sheets it should solve this issue.

**Comment by vigneshhari** [comment]
Once we deploy the CSV at midnight we can start to try this, looks relatively straightforward.

**Comment by jitendraag** [comment]
We have hit a roadblock on integromat / apipheny side. Can we please see if the CSV to sheet solution has legs?

**Comment by vigneshhari** [comment]
@shrihari689 the CSV dumps are already configured, can you connect them with google sheets as specified earlier?

**Comment by vigneshhari** [comment]
@shrihari689 wrote an appscript for this
The data is now available at https://docs.google.com/spreadsheets/d/1Oyuf3LOjBr_ubJOJCTlBk6ODg3jXiSlLMW9g4-m5SHU/edit?usp=sharing and updated every 15 mins

**Comment by bodhish** [comment]
@shrihari689 add it to Readme.
