### ISSUE TITLE
Add sign-up form link to 'integrate data page'

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#217]
**Is your feature request related to a problem? Please describe.**
We recently made a 'how to integrate data' page. This is a great start. However, people still need more communication, handholding and we need to collect their details.

We should add http://bit.ly/JoinForces-CovidReliefIndiaAlliance URL with more text to the page.

**Describe the solution you'd like**
Change https://liferesources.in/how_to_integrate_data

Include this message:
For all collaboration related enquiries: If you are another initiative wanting to join hands, we are a part of Covid India Relief alliance, where 10+ initiatives have agreed to work on ONE backend - consolidation of database to prevent redundancy and duplicacy of volunteer efforts in data addition, verification, updation. Fill this form  http://bit.ly/JoinForces-CovidReliefIndiaAlliance
Feel free to share this form with other initiatives to integrate with the alliance, in case they are doing the same thing as - database addition verification updation. It is being coordinated by Aakriti, Prajakta, Nameet, Ashish over a whatsapp group. The first step would be to fill the form above. Thanks!

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by shrihari689** [comment]
Completed 🚀
