### ISSUE TITLE
Generate verified data APIs / files

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#220]
**Is your feature request related to a problem? Please describe.**
Currently we are generating JSON and CSV for ALL of our data. It makes sense for us to also provide APIs which returns only verified data. This can be used by bots, SOS workers etc.

**Describe the solution you'd like**
Generate extra JSON and CSV files that eliminate unverified data.

**Describe alternatives you've considered**
Clients are filtering data today

**Additional context**
NA

**Comment by shrihari689** [comment]
Completed as of https://github.com/coronasafe/life/commit/465ada84701315d940b4f4986e3eee4b85081e7b and https://github.com/coronasafe/life/commit/7e566efd60a44610968592385a6d827cd37ef4c4 📍

Summary: 
- Exposed new API endpoints where users can get only verified data of specific resource type. 🎉
Explore: https://life-api.coronasafe.network/
