### ISSUE TITLE
For twitter results human readable time would be good

### ISSUE THREAD

**Issue by technoknol** [coronasafe/life#224]
**Is your feature request related to a problem? Please describe.**
During this time, TIME is very crucial thing. Twitter results are showing in date and time format. That will be little difficult for information seeker. 

**Describe the solution you'd like**
For twitter results if we can show time in human readable format like (30 seconds ago, 1 day ago) would be a great help for information seeker. This will help him interpret information quickly and get an idea about how latest information is. 

Let me know your thoughts. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by bodhish** [comment]
This would be a super useful feature

**Comment by shrihari689** [comment]
Completed 🚀

**Comment by technoknol** [comment]
This is not deployed yet ? @shrihari689

**Comment by shrihari689** [comment]
Its live 📌

![image](https://user-images.githubusercontent.com/57325503/116731869-e8133d00-aa07-11eb-83ba-3d920cee4599.png)

**Comment by technoknol** [comment]
Ohh, may be I was checking cached version. Thanks.
