### ISSUE TITLE
Update FE to consume V2 schema

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#226]
Consume the new v2_json and update the cords. 
Create empty files for the data that we don't have now. 

example: 

medicine_v2.json 
```
{ 
  data: []
}
```

**Comment by bodhish** [comment]
@Deep-Codes use #225 as base

**Comment by Deep-Codes** [comment]
> @Deep-Codes use #225 as base

Alright Noted

**Comment by shrihari689** [comment]
Completed as of this https://github.com/coronasafe/life/pull/225 📌
