### ISSUE TITLE
Create a data conversion project

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#231]
The current JSON on the master bucker is going to grow over time. 
Also considering the request that there should be an option for other bots to just fetch data for a district.

We have decided to start a new project that will handle the data translations. 

It can be a new Github repo that will do the following actions. 
- [x] Downloads the master JSON/CSV every 30 mins 
- [x] @shrihari689 Converts the data into multiple folders and files in such a way that every district will have a JSON file for each category. 
```
data/kerala/ernakulam/oxygen.json
data/kerala/ernakulam/hospitals.json
```

- [x] @shrihari689 Create a serverless function [serverless](https://github.com/serverless/serverless) that will respond to the user requests. (API). The function should identify the file based on the inputs and return the file contents in a random order for each request. (Just a small function to randomize the array) 

note:  The 1st 2 steps could be done by adopting the scraper from this repo (keep it in python itself).

**Comment by bodhish** [comment]
FYI: @karmakoder could onboard you to the new repo https://github.com/coronasafe/life-data

**Comment by bodhish** [comment]
@tomahawk-pilot could help you deploy once the changes are live.

**Comment by bodhish** [comment]
All the endpoints have cf proxy enabled

**Comment by bodhish** [comment]
I just got an alternate thought do we need the serverless. The scraper could simply randomise the order evry 10 mins.

The frontends can always order data so even if we put in infra they may order it / randomise it the way they want.

Should we just reorder it every 10 mins. Would be pretty straightforward.

Splitting the chuck will help a lot of people who could just consume bits from the whole data.

**Comment by technoknol** [comment]
We can deploy on Cloudflare workers. Free version gives 1,00,000 hits / day. We can ask favor for premium plan as well. Thougts ?

**Comment by divyagar** [comment]
I would like to work on this issue. @karmakoder can you onboard me?

**Comment by shrihari689** [comment]
I can also take part in this 📌🙌

**Comment by karmakoder** [comment]
@divyagar @shrihari689 thx. Am trying to figure out if i need to add u guys as a member to repo. In the meantime, can u plz look at first 2 checkboxes in bodhi's description? Downloads the master JSON/CSV ever 30 mins and Converts the data into multiple folders and files in such a way that every district will have a JSON file for each category. Thx.

**Comment by shrihari689** [comment]
I am on it 📍 
- [ ] Converts the data into multiple folders and files in such a way that every district will have a JSON file for each category.

**Comment by karmakoder** [comment]
> FYI: @karmakoder could onboard you to the new repo https://github.com/coronasafe/life-data

@bodhish shud i create a new team in github for life-data or create a team inside Life team?

**Comment by karmakoder** [comment]
> I am on it 📍
> 
> * [ ]  Converts the data into multiple folders and files in such a way that every district will have a JSON file for each category.

@shrihari689 keep this in mind plz : note: The 1st 2 steps could be done by adopting the scraper from this repo (keep it in python itself).

**Comment by shrihari689** [comment]
Yeah 🎉 Doing it in Python

**Comment by karmakoder** [comment]
The serverless function cud use python's random.choices e.g. https://stackoverflow.com/questions/56309256/how-to-randomly-select-from-a-json-file

**Comment by karmakoder** [comment]
@bodhish whr shud the split jsons like following be created? In the same S3 that is housing the rest of jsons?

> data/kerala/ernakulam/oxygen.json
> data/kerala/ernakulam/hospitals.json 

Also, @tomahawk-pilot can u plz start prep for a lambda with an IAM role that has read-only access to the S3 bucket in question. Plz keep timeout for lambda large enuf like 5 mins and the memory to be around 1024 MB. Thx.

**Comment by shrihari689** [comment]
🎉
Completed creating a scrapper and dumping files for each district and state with each resource type 📍

Waiting for repo access to push 📌

**Comment by karmakoder** [comment]
> 🎉
> Completed creating a scrapper and dumping files for each district and state with each resource type 📍
> 
> Waiting for repo access to push 📌

kewl @shrihari689 how about _The serverless function cud use python's random.choices e.g. https://stackoverflow.com/questions/56309256/how-to-randomly-select-from-a-json-file_

**Comment by shrihari689** [comment]
Completed the `Converts the data into multiple folders and files in such a way that every district will have a JSON file for each category` and made a simple function that randomizes things 🎉

Any update about serveless part? @bodhish  📌

**Comment by shrihari689** [comment]
Completed 🚀 and under improvement 📍

https://life-pipeline.coronasafe.network/

@bodhish  @vigneshhari
