### ISSUE TITLE
Faster feedback mechanism on website / API

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#239]
**Is your feature request related to a problem? Please describe.**
Currently, we are spending a lot of time and effort working with volunteers to verify and re-verify data. We also have a massive influx of people trying to use our data to help their friends and family.

These covid victims are also in a position to give us excellent feedback on quality of data. If this feedback mechanism is available on our website and in our APIs our data verification status will remain 'current'.

**Describe the solution you'd like**
Add a UI inspired by the verification app and allow real users to give us feedback in real-time.

<img width="440" alt="Screenshot 2021-05-01 at 10 25 58 PM" src="https://user-images.githubusercontent.com/3295926/116789410-46a1ef00-aacc-11eb-8b37-e60c5c313eae.png">

On API side - allow third party apps to send real-time feedback using secret key allocate by us.

Use SQS or other queue mechanism with appropriate hash key to prevent database write surges.

Future versions:
1. Sheet owners can know about quality of their leads from batch emails
2. Provide sheet owners API webhooks about quality of their data

**Describe alternatives you've considered**
We have an offline verification synchronization mechanism running on the back of volunteer efforts.

**Additional context**
This change has the potential to make our data immensely more real-time and usable.

**Comment by PallabiRoy27** [comment]
For _potentially fraud_ - I have a list of such leads and can share them for the database.

**Comment by chicksim** [comment]
Some suggestions: 

1. Upvote downvote and Button fields for feedback may clash and confuse people. Upvote downvote doesn't give us granularity in the information - like why was it downvoted (not picking up? stock unavailable? wrong number? Invalid - doesn't deal with oxygen?)
2. For the above reason I prefer buttons. the flow should be: 

Submit Feedback> (choose) 1. Available and Verified (helper text: person picked up the call, and said resource is available); 2. Unavailable but verified (helper text: person picked up call, currently stock unavailable, may come later); 3. Invalid (helper text: Wrong number or doesn't deal in this, please remove); 4. Unresponsive (not picking up the call or busy); 5. Potential fraud (helper text: The person was charging advance payment, and sounded to be a scamster. Please report. Our team will inform FDA/relevant authorities to look into it)

Report fraud - can be a different button too. 

this feature is very important. 

Doubts: 
1. Will this feedback go back to the source google sheet and be captured in a new column there on the row? based on the ID field mapping (best case scenario). then they will be able to modify and work on such flagged rows
2. Will this go to the source sheet in the form of regular emails? like we do for CSV parsing errors. This can also help notify the initiative. But the option 1 is easiest, as they wont have to go back and forth and check where the data is. 

this is the 2 way flow we were talking about.

**Comment by jitendraag** [comment]
My recommendations below:
https://www.notion.so/jiten/COVID-resource-verification-methods-d89e7800b7064731933989086342b815

Only SOME partners are allowed to change verification status
+
[LifeResources.in](http://liferesources.in) and partners use an API (secret key) to mark things as 'verified and available' (Other options not available)
