### ISSUE TITLE
Show Bed / Oxygen cylinder availability on UI whenever data is available

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#240]
**Is your feature request related to a problem? Please describe.**
We are collecting more and more data using our volunteer verifier and other networks. Among the most important element is number of beds, cylinders available with a hospital / vendor. Covid victims should be able to make an informed decision about calling vendors based on availability.

**Describe the solution you'd like**
Add availability numbers for resources wherever they are available.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by karmakoder** [comment]
The new UI does display the quantity available. It's a string so sometimes it just shows Available which is all based on the data entered on the g sheets. This can be closed I think @jitendraag @khavinshankar
