### ISSUE TITLE
Show verified results before unverified results

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#241]
**Is your feature request related to a problem? Please describe.**
Currently we show all results by default and results are not sorted based on verification status. Someone trying to find resources for their friends and family would prefer to see verified resources first. Only if the verified resources don't work, they are likely to try unverified resources. We should sort our results based on verified first.

**Describe the solution you'd like**
We should store json files with verified data first.

<img width="1573" alt="Screenshot 2021-05-01 at 11 05 31 PM" src="https://user-images.githubusercontent.com/3295926/116790446-c9797880-aad1-11eb-88d6-7f65ef470312.png">

**Describe alternatives you've considered**
Have verified button clicked by default instead of "Show all" is a valid option too

**Additional context**
NA

**Comment by rakeshgunduka** [comment]
@khavinshankar If this issue is not resolved. I can provide a quick fix for this.
Let me know

**Comment by rakeshgunduka** [comment]
@jitendraag
