### ISSUE TITLE
All Key fields in v2 API json response to lower case

### ISSUE THREAD

**Issue by ganeshsp1** [coronasafe/life#247]
**Describe the bug**
For all the responses of v2 API the following key start with capital letter :
"Assigned_to"

**To Reproduce**
Just fire any API request 

**Expected behavior**
All json keys should be lower case like "assigned_to" for the ease of parsing. 

**Screenshots**
NA

**Desktop (please complete the following information):** NA
- OS: [e.g. iOS]: 
- Browser [e.g. chrome, safari] : 
- Version [e.g. 22]: 

**Smartphone (please complete the following information):** NA

**Additional context**
NA

**Comment by vigneshhari** [comment]
All required fields are already in lowercase ( snake_casing ), Any other attributes are not managed by us, Please build a pipeline to generate a standard file as per your requirement.

**Comment by vigneshhari** [comment]
@tomahawk-pilot can guide you to create a new pipeline, you can clone our existing pipeline as well.

**Comment by shrihari689** [comment]
Closing this as of `wontfix` 📍
