### ISSUE TITLE
Incorrect state spelling (capital letters) results into an empty set

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#252]
**Describe the bug**
`curl -ik "https://life-pipeline.coronasafe.network/api/resources?resource=oxygen&state=Maharashtra&district=latur"
`
Capital **Maharashtra** in query returns an empty response and not 404.

`curl -ik "https://life-pipeline.coronasafe.network/api/resources?resource=oxygen&state=maharashtra&district=latur"
`

Small **maharashtra** works

**To Reproduce**
1. Use curl to see the issue

**Expected behavior**
1. We should allow any case (lower / capital) for state and district names
2. We should document that _ is used for states like uttar_pradesh

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by shrihari689** [comment]
1️⃣ Fixed 🙈 (as priority)

`resources?resource=oxygen&state=Tamil Nadu&district=Chennai` works ✅
`resources?resource=Medicine&state=Tamil Nadu&district=Chennai` works ✅
`resources?resource=medicine&state=tamil_nadu&district=chennai` works ✅
`resources?resource=medicine&state=Tamil_nadu&district=Chennai` works ✅

2️⃣ Needs to be documented 📍 Will be doing that 🎉

**Comment by shrihari689** [comment]
📍 Resolved
