### ISSUE TITLE
Cards should have an option to register upvote / downvote.

### ISSUE THREAD

**Issue by ProCode2** [coronasafe/life#255]
**Is your feature request related to a problem? Please describe.**
Cards should have an option to register upvote / downvote .

**Describe the solution you'd like**
Cards should have an option to register upvote / downvote. Also, store the details on local storage so that they can't abuse the endpoints.

**Comment by shrihari689** [comment]
📌

https://github.com/coronasafe/life/blob/39f94cad3eebca0698e173d71c04fdd920f8b4d3/components/ResourceCard.jsx#L169

https://github.com/coronasafe/life/blob/main/components/FeedbackCounter.jsx
