### ISSUE TITLE
Switch tab to Twitter results when no data results received

### ISSUE THREAD

**Issue by sam9111** [coronasafe/life#256]

**Comment by peeyush14goyal** [comment]
I already fixed this previously. in PR #234 Please check

**Comment by sam9111** [comment]
Got it👍

**Comment by shrihari689** [comment]
The issue @peeyush14goyal solved (3 days ago) has been replaced by my code 😿 while I was migrating to v2 API 📍
Now if you do a search the Twitter Card will be shown in the Result Tab. It doesn't switch tab 📌

So @Sandra3657  and @sam9111  you may continue to work 🎉
