### ISSUE TITLE
Not showing Verified results

### ISSUE THREAD

**Issue by peeyush14goyal** [coronasafe/life#261]
**Describe the bug**
Verified button does not show verified results it shows " No results"

**Screenshots**
![image](https://user-images.githubusercontent.com/42883572/116968064-5dfdf980-acd1-11eb-8c26-4c42682f96c6.png)
![image](https://user-images.githubusercontent.com/42883572/116968091-69e9bb80-acd1-11eb-8e04-a499a8254ae8.png)

**Desktop**

**Comment by shrihari689** [comment]
Closing as of #263 📌
