### ISSUE TITLE
Section not clickable

### ISSUE THREAD

**Issue by namanambavi** [coronasafe/life#265]
**Describe the bug**
When I click on a state and it automatically takes me to the twitter section out of the 3 (results,twitter & map). There are no tweets and that’s okay but then I can’t shift to the results section. It falls back to the twitter section only. 

**To Reproduce**
1. go to the homepage
2. Select a state
3. Try to change from twitter to results
4. It won’t happen (attaching video)

**Expected behavior**
The section should be clickable

**Screenshots**

https://user-images.githubusercontent.com/49127970/117103452-070f2780-ad98-11eb-8d51-1492e5f13d71.MP4

Smartphone
-Device: iPhone 12
- OS: iOS15
- Browser: Safari

**Comment by bodhish** [comment]
Hide results section if the results are not available. 

Currently clicking on the results tab is forwarding the user to Twitter tab as their are no entries avilable for the selected district.

**Comment by tecnoder** [comment]
I can look into this issue
