### ISSUE TITLE
Move all mandatory fields at the top (or left) of documents

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#276]
**Is your feature request related to a problem? Please describe.**
When I try to explain mandatory fields to data partners, it's often confusing for them to know that a field coming at position 15 is mandatory.

**Describe the solution you'd like**
I propose we change the order of fields in following page:
https://github.com/coronasafe/life/wiki/Life-Data-Structure
phone_1, district and state fields must be moved up.

Similarly, the fields should move to left on all our Google sheets.
* https://docs.google.com/spreadsheets/d/1I_V1K4pEoz1omlMaYC7tZScMYMlGAYBXzVpuvspws7E/edit#gid=0
* https://github.com/coronasafe/life#api-v2-csv

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by shrihari689** [comment]
Done with https://github.com/coronasafe/life/wiki/Life-Data-Structure 📍

**Comment by shrihari689** [comment]
Done with Spreadsheet (https://docs.google.com/spreadsheets/d/1I_V1K4pEoz1omlMaYC7tZScMYMlGAYBXzVpuvspws7E/edit#gid=0) too 🎉


Note: Since CSV is from backend, we could not update the order there 📍😿
