### ISSUE TITLE
Default district selection for Andhra Pradesh is Anantpur

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#279]
**Describe the bug**
When I go to Andhra Pradesh page and want to see Twitter results the page is empty by default.

**To Reproduce**
1. Go to 'https://liferesources.in/andhra_pradesh'
2. Click on 'Twitter'
3. See error

**Expected behavior**
By default 'all districts' should be selected and results for all districts should be shown

**Screenshots**
![Screenshot 2021-05-05 at 9 23 22 AM](https://user-images.githubusercontent.com/3295926/117168006-6a737680-ade5-11eb-8dbc-e7866d3615ff.png)

**Desktop (please complete the following information):**
All OS and browsers

**Smartphone (please complete the following information):**
Desktop

**Additional context**
This is a sort of problem for normal results too.

**Comment by shrihari689** [comment]
Resolved 📍
