### ISSUE TITLE
Add link to home page

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#28]
Add a link to the homepage on the home icon

![image](https://user-images.githubusercontent.com/14979190/115887690-cd711f00-a46f-11eb-9cbb-2d3836308bae.png)

**Comment by shrihari689** [comment]
Isn't this already done ? 🤔https://life-coronasafe.vercel.app/maharashtra/kolhapur/medicine
I am able to click 📍

**Comment by karmakoder** [comment]
works for me too @shrihari689 @bodhish.

**Comment by Deep-Codes** [comment]
Works Now!
