### ISSUE TITLE
Compute top 10 states and districts 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#280]
Write a python script that could pass through the V2 data and create the `data/top_states_and_districts.` file. 

The logic can be simple. Count the number of resources in each district and state with the python script and write it to a JSON file. 

This file can also be used for aggregating the summary data shown on the home page related to the data that is available.

**Comment by shrihari689** [comment]
Resolved as of https://github.com/coronasafe/life/commit/29f4ac85478472971c15a71d6bfd20a402a98e8a and https://github.com/coronasafe/life/commit/eead5cd6c510309f43e142f4700a8b9f0a49046f 📍
Now the Top States and Districts is dynamic 🚀
