### ISSUE TITLE
[Semantic Bug] State or District's page does not opens up from search bar on click

### ISSUE THREAD

**Issue by aayushsaini** [coronasafe/life#284]
**Describe the bug**
State's or District's page does not opens upon clicking on the suggested cards when typing the name in search box

**To Reproduce**
1. Go to 'Home page: https://life.coronasafe.network '
2. Click on 'Search bar'
3. Enter the name of the state/district (e.g. type 'Chan' for 'Changlang')
4. Upon clicking on the suggested name cards for the typing input, it does not open the page for that district/state

**Expected behavior**
Should work just as it works on the mobile devices i.e., upon tapping(clicking) on the suggestion, the respective page should open up.

**Screenshots**
1.  Upon clicking on the 'Changlang' or any district or state from the given suggested cards, it takes to the Img 2 screen
![0](https://user-images.githubusercontent.com/31177925/117317834-7fb0d980-aea7-11eb-84fd-3557f996b557.png)

2. After clicking the suggested cards this screen shows up, let's say I typed 'Chan' for 'Changlang' but as per suggestion it shows Chandigarh and even after clicking on 'Changlang' suggested card it shows this screen with 'Chandigarh' in the text
![1](https://user-images.githubusercontent.com/31177925/117317842-817a9d00-aea7-11eb-948a-a98f4a844062.png)

**Desktop (please complete the following information):**
- OS: Windows 10, Mac OS Big Sur 11.3
- Browser: Brave, Chrome, Edge, Safari
- Version [Latest builds of all of the above]

**Smartphone (please complete the following information):**
- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Comment by shrihari689** [comment]
Is this happening for anyone else @coronasafe/life  😿?

**Comment by divyamangra** [comment]
unable to simulate:
OS: Windows 10
Browser: Chrome, Opera, Edge
version: Latest versions

**Comment by aayushsaini** [comment]
Strange that it has occurred on both of windows & Mac laptop. I would give a final update regarding the same tomorrow.

**Comment by aayushsaini** [comment]
The bug still persist, I assume it is a device specific bug. I'll open a PR if it is otherwise solvable.
Thank you!
