### ISSUE TITLE
Theme button at navbar is not mobile responsive

### ISSUE THREAD

**Issue by arihant-2310** [coronasafe/life#285]
The theme button on the right of the navbar is not visible completely on small screen devices.

1. Go to https://life.coronasafe.network/ in mobile view.
2. Notice the theme button at the top right.
3. See an error

![image](https://user-images.githubusercontent.com/36256102/117325973-d968d200-aeae-11eb-923c-854ea5936520.png)

**Comment by shrihari689** [comment]
![image](https://user-images.githubusercontent.com/57325503/117329057-e1764100-aeb1-11eb-8bc9-0036b1761446.png)
 Resolved 🚀
Thank You @arihant-2310 🎉
