### ISSUE TITLE
LinkedIn/Facebook sharing broken

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#290]
**Describe the bug**
Tried to share a resource on LinkedIn - The link says undefined.

**To Reproduce**
1. Go to 'https://liferesources.in/andhra_pradesh'
2. Click on 'LinkedIn or Facebook buttons'
3. See error - https://www.linkedin.com/shareArticle?mini=true&url=undefined or https://www.facebook.com/sharer/sharer.php?u=undefined

**Expected behavior**
These should have correct sharing properties like (copy and twitter)
For example:

```
Name: Mr.Gandhi Prasad 
Contact: 9492733337 
More Info: https://liferesources.in/andhra_pradesh#869e417a-102e-40fc-91f8-aa26cd2b66b5 

https://twitter.com/intent/tweet?text=Name:%20Mr.Gandhi%20Prasad%20Contact:%209492733337%20More%20Info:%20https://liferesources.in/andhra_pradesh#869e417a-102e-40fc-91f8-aa26cd2b66b5

```

**Screenshots**
NA

**Desktop (please complete the following information):**
- OS: Mac
- Browser: Chrome
- Version 90.0.4430.93 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by shrihari689** [comment]
Fixed 📍
