### ISSUE TITLE
Bugs in Delhi (NCT) flow

### ISSUE THREAD

**Issue by n3jain** [coronasafe/life#291]
**Describe the bug**
When I select Delhi (NCT) all there is no live twitter feed. 
When I select West Delhi, there are no results 
After that if I select any other region and there are results - error message No message still shows up.

**To Reproduce**
1. Go to Delhi (NCT)
2. Click on Twitter
3. Select "West Delhi"
5. Select "South Delhi"
6. Still see error

**Expected behavior**
Twitter results for all Delhi should show, Error message for no results should not persist for a scenarios when results are available.

**Comment by jitendraag** [comment]
I can confirm that the issue exists on Chrome Macbook too.

**Comment by peeyush14goyal** [comment]
Error message for no results is when we do not have any in database result.

**Comment by peeyush14goyal** [comment]
But there is a similar issue. If I select a district with database results after choosing a district with no database results then by default it renders current tab results only and shows error message 
![image](https://user-images.githubusercontent.com/42883572/117527996-9a8d6600-afed-11eb-8d98-ea76654709fd.png)

**Comment by shrihari689** [comment]
@peeyush14goyal Doing this?

**Comment by peeyush14goyal** [comment]
Sure

**Comment by peeyush14goyal** [comment]
@n3jain @jitendraag @shrihari689 Please review #293. I have resolved the issue in this PR.

**Comment by shrihari689** [comment]
Resolved via #293 📍
