### ISSUE TITLE
Wrong Verified status 

### ISSUE THREAD

**Issue by ganeshsp1** [coronasafe/life#296]
**Describe the bug**
Website showing wrong verified data as below :
From API  :
{
      "state": "Maharashtra",
      "district": "Mumbai City",
      "state_id": "22",
      "district_id": "378",
      "data_name": "Verification App from Ruchika",
      "external_id": "179b6fcd-cc5c-4ab6-97e9-5d6a70a1809f",
      "data_id": "813",
      "category": "oxygen",
      "phone_1": "955454414",
      "is_duplicate": false,
      "downvotes": 0,
      "upvotes": 0,
      "created_job": 4,
      "city": "",
      "email": "",
      "price": "",
      "title": "10L cylinders Maharashtra Health care",
      "address": "",
      "comment": "Pending",
      "deleted": false,
      "phone_2": "",
      "pincode": "",
      "created_by": "",
      "created_on": "",
      "description": "",
      "source_link": "https://twitter.com/intent/tweet?url=https%3A%2F%2Findiacovidresources.in%2F&text=",
      "verified_by": "",
      ":lock: Row ID": "YWzFtz6jTSyBNSDdtGsE.Q",
      "resource type": "",
      "Selected By User": "",
      "last_verified_on": "4/27/2021 2:25pm",
      "Verification Image": "https://drive.google.com/file/d/1K4Z8jpGUKFSHMu0xSE1tFtmyUAsXl-29/view?usp=sharing",
      "quantity_available": "",
      "verification_status": "pending (not verified)",
      "hospital_available_icu_beds": "",
      "hospital_available_normal_beds": "",
      "hospital_available_oxygen_beds": "",
      "hospital_available_ventilator_beds": ""
    },
Data on website shows this as verified

**To Reproduce**
1. Compare Website Data with API

**Expected behavior**
The resource should not show false verified, creates a false sense of  credibility.

**Screenshots**
![image](https://user-images.githubusercontent.com/3330429/117559170-d2091a80-b0a0-11eb-8a7b-8f9cada586e0.png)

**Additional context**
Can we have a set of predefined set of verification statuses?
Please find below the list of verification statuses I found from some of the APIs
"Available and verified", "Call again", "", "Invalid", "not verified", "Pending", "pending (not verified)", "3rd_party_verified", "unavailable", "Unavailable but verified", "unreachable", "Unresponsive", " ", "Pending ", "Verified", "verified", "verified and available", "bogus"

**Comment by raeesaa** [comment]
Can I look into this?

**Comment by raeesaa** [comment]
I am getting following error when trying to run code locally. 

![image](https://user-images.githubusercontent.com/4486873/117675844-92d6e880-b1ca-11eb-9630-733a0c37f810.png)

I followed the steps given in README file. Can someone guide me with this?

**Comment by khavinshankar** [comment]
@raeesaa I fixed this issue, so please feel free to work on different issue.
