### ISSUE TITLE
Districts not getting updated in frontend

### ISSUE THREAD

**Issue by bodhisha** [coronasafe/life#299]
The districts mentioned below are present in the backend but are not updated on the frontend. 
 - Tirupathur
 - Tenkasi
 - Kallakurichi
 - Chengalpattu

**Comment by shrihari689** [comment]
Added these districts as of now 📌 Can you please change in our General Structure too ? 🚀

**Comment by bodhisha** [comment]
Done.. 👍

**Comment by bodhisha** [comment]
Add these districts also @shrihari689 

-   Jhargram
-   Purba Burdwan (Bardhaman)
-   Paschim Burdwan (West Bardhaman)
