### ISSUE TITLE
integrate feedback API and collect feedbacks 

### ISSUE THREAD

**Issue by smartclash** [coronasafe/life#301]
A feedback collection API has been deployed at [life-pipeline](https://life-pipeline.coronasafe.network/api/feedback) from [life-data](https://github.com/coronasafe/life-data) and needs to be integrated into this project. Checkout it's [documentation](https://github.com/coronasafe/life-data/wiki/Feedback-API)

The user will be allowed to choose one of many feedback choices provided by the API and has to undergo a captcha verification. The captcha response key should be sent along with the choice to the API for it to be recorded.

Fixes #160, #239, #255.
Related #58

**Comment by smartclash** [comment]
Anyone good with frontend, do ping and pair up with me if free. Would love a helping hand :wink:

**Comment by brainless** [comment]
@smartclash I can pair up with you, have React/Tailwind experience.
