### ISSUE TITLE
Inner pages are losing all js actions on load if the link is directly loaded

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#32]
Example https://life.coronasafe.network/delhi_(nct)

**Comment by Deep-Codes** [comment]
Doesn't seem to be a Problem with Vercel Deploys

Example: https://test-coronsafe-life.vercel.app/chhattisgarh

**Comment by karmakoder** [comment]
![Screen Shot 2021-04-23 at 3 33 12 PM](https://user-images.githubusercontent.com/5466439/115921405-6f314580-a449-11eb-9fbc-3f33e32fcc5f.png)

**Comment by vandanabhandari** [comment]
looks like this issue is already fixed @karmakoder plz verify and close.

**Comment by Deep-Codes** [comment]
> looks like this issue is already fixed @karmakoder plz verify and close.

Yes It's fixed Now 🎉🚀

Closing.
