### ISSUE TITLE
phone numbers displayed in varied forms

### ISSUE THREAD

**Issue by Deep-Codes** [coronasafe/life#33]
<img width="300" alt="Screenshot 2021-04-24 at 12 04 30 AM" src="https://user-images.githubusercontent.com/61158210/115915266-bbec3f00-a490-11eb-967f-6e12f4285322.png">

Link: https://life.coronasafe.network/maharashtra/mumbai_city/ambulance

**Comment by karmakoder** [comment]
Saw these issues with data entry. Anyway to prevent this happening in airtable?

**Comment by viksit** [comment]
yes, you can use this: https://community.airtable.com/t/standard-formatting-for-phone-numbers/23684

@karmakoder

**Comment by hectarV** [comment]
@karmakoder who is looking into this ?

**Comment by karmakoder** [comment]
thats a good tag to add @Deep-Codes. BTW can u help me with access so i can triage open issue? am still not able to assign among our group of devs.

**Comment by Deep-Codes** [comment]
> thats a good tag to add @Deep-Codes. BTW can u help me with access so i can triage open issue? am still not able to assign among our group of devs.

Since you're a member you have access to assign people to issues. 🤔

**Comment by karmakoder** [comment]
Do the people need to be member of the group/repo? I tried assigning to @kashyapshankhavara and @rawris but cudnt. Wonder what am missing @Deep-Codes.

**Comment by Deep-Codes** [comment]
> Do the people need to be member of the group/repo? I tried assigning to @kashyapshankhavara and @rawris but cudnt. Wonder what am missing @Deep-Codes.

 @kashyapshankhavara and @rawris haven't commented here so they don't come up in the list.

As you can see 2 people can be added as they have commented above

<img width="324" alt="Screenshot 2021-04-24 at 5 06 22 AM" src="https://user-images.githubusercontent.com/61158210/115939156-d20ef500-a4ba-11eb-85a7-de9d4fc244f2.png">

Also if the person is a member he/she can be added to the issue regardless of commenting.

**Comment by karmakoder** [comment]
> @karmakoder who is looking into this ?

@hectarV no one from our team has picked this one yet. Wud u like to?

**Comment by ProCode2** [comment]
The data needs to be cleaned right? The front end is not parsing/cleaning the `phone1` string right now.

**Comment by hectarV** [comment]
@karmakoder I will pick this up

> > @karmakoder who is looking into this ?
> 
> @hectarV no one from our team has picked this one yet. Wud u like to?



> > @karmakoder who is looking into this ?
> 
> @hectarV no one from our team has picked this one yet. Wud u like to?

I will pick it up

**Comment by hectarV** [comment]
@Deep-Codes I have created a pull request for this.

**Comment by karmakoder** [comment]
handled in https://github.com/coronasafe/life/pull/98. closing.
