### ISSUE TITLE
under city name, non clickable boxes are highlighted while clickable boxes seems like disable in dark mode [Low priority]

### ISSUE THREAD

**Issue by shubhSaxena** [coronasafe/life#35]
Steps- 
1. open site in dark mode
2. click on any state 
3. not clear which ones are active and which ones are disable boxes, under city name
4. active and non active look like they are interchanged.
<img width="1407" alt="Screenshot 2021-04-24 at 1 16 34 AM" src="https://user-images.githubusercontent.com/9431863/115923313-adefeb80-a49b-11eb-9d58-583985cca864.png">
<img width="1433" alt="Screenshot 2021-04-24 at 1 16 46 AM" src="https://user-images.githubusercontent.com/9431863/115923323-b21c0900-a49b-11eb-9800-be0dbbfce745.png">

**Comment by Deep-Codes** [comment]
yeah i am looking into the issue prev it showed colors for those which were active.

**Comment by Deep-Codes** [comment]
@shubhSaxena Check now https://life.coronasafe.network/uttar_pradesh
