### ISSUE TITLE
service worker and pwa

### ISSUE THREAD

**Issue by tomahawk-pilot** [coronasafe/life#36]
lets add a service worker and make life a pwa
https://dev.to/josedonato/adding-a-service-worker-into-your-next-js-application-1dib
https://itnext.io/pwa-with-next-js-create-next-app-in-2020-%EF%B8%8F-9ee0e1a6313d

**Comment by tomahawk-pilot** [comment]
are you taking this @Deep-Codes  ? or should i do it

**Comment by Deep-Codes** [comment]
> are you taking this @Deep-Codes ? or should i do it

You take it , I would work on the `meta tags` one

**Comment by tomahawk-pilot** [comment]
ok
