### ISSUE TITLE
STATS display on home page

### ISSUE THREAD

**Issue by chicksim** [coronasafe/life#40]
A dynamic counter ticker kind of simple UI design  on the gap between footer and states that shows:

3178 Hospitals   452 Ambulance 
466 verified         23 verified

This will show the scale of the data that we have. And we would be transparent too on how much more is left to be verified. May be this would nudge ppl to join us, giving them a sense of feel that - ok they need help with verificationss I should join then

Stats could be of - all the fields, and also number of volunteers. The volunteers database is on the airtable itself. So you have real time update on no. of volunteers too.

**Comment by ProCode2** [comment]
@karmakoder any update on this?

**Comment by karmakoder** [comment]
> @karmakoder any update on this?

https://github.com/coronasafe/life/pull/99 @ProCode2
