### ISSUE TITLE
Pending for verification cards could become tasks using automation?

### ISSUE THREAD

**Issue by chicksim** [coronasafe/life#41]
Mark all the data on airtable that has blank or not verified status as pending for verification. Use some automation to create cards/tasks like freshdesk or Jira or something. 

Ideas: 
1. On airtable auto assign it to people. So that every day they know these are the numbers we are verifying
2. Even if we don't assign, have a task page where we see only unverified contacts. Then verification can happen on a different place than airtable, and be automatically populated on airtable, after Jira task is completed. This will prevent the chaos when both addition, updation, verification, and formatting of the airtable happen simultaneously, the volunteers lose their track of data. 
2. Display them on frontend on a page 'Help us verify pending contacts' if you open the link it will show all cards on the site for a state or resource chosen, that is not verified. A normal public can keep calling it and update it from there? This is dependent on the assumption that form view link can it open for an existing field (can we edit an existing database using form view/airtable forms)

**Comment by chicksim** [comment]
something like freshdesk/freshworks tickets or Jira tasks or Mturk kind of a thing? This is to keep verification activities and database addition different. There is merit in this. People see only the card they need to verify. and can move on to the next task. We can reward them with - Ok Simran verified 50 contacts today. Leaderboard.

**Comment by chicksim** [comment]
Once a viewer contributes to the form or a volunteer adds a row to the airtable database, it automates a task generation for it to be verified - i.e. someone needs to pick up that task to fill the 3 columns - verification status, verified by, verifier comments - fields. A verification volunteers sees all these tasks on freshdesk/jira or whatever task management portal is connected to airtable. This way we can separate verifiers with data cleaners

**Comment by bodhish** [comment]
closing artable issues
