### ISSUE TITLE
Add more fields to cards that we are collecting for some resources

### ISSUE THREAD

**Issue by chicksim** [coronasafe/life#43]
Eg.  new fields that we are collecting and would be super helpful to show. Could we find a way to show this. A simpler way would be to merge all this information together in a string under description (concatenate kinda)

**Hospital -** 
Type of Hospital
Verifier_Comment - Instructions, guidelines, latest update available from hospital
Sub category of hospital- what type of hospital this is
Availability - Yes or No
Type of bed available - covid/non covid/with o2/with ventilator/with icu
How many beds available when you last checked

Similarly we have more helpful information for each field type, will add them below later. But this might require creating different views/card layout for different resource type - hospital, oxygen etc. 

But this is super valuable as it enhances the depth of information we are providing. Show these at least wherever available

**Comment by karmakoder** [comment]
@bodhish @tomahawk-pilot @Deep-Codes plz advise how we can view the json datamodel behind the API calls to fix this issue. Looks like on local we are just using data from the static json files and the API_KEY is correctly obfuscated now. <insert scratching head emoji here> 😄

**Comment by bodhish** [comment]
@divyagar

**Comment by divyagar** [comment]
@bodhish @karmakoder I have added new fields in json.

**Comment by Deep-Codes** [comment]
@divyagar Solved?

**Comment by divyagar** [comment]
@Deep-Codes  I am currently not working on this issue.

**Comment by karmakoder** [comment]
Was trying to display this data and this is whats in the jsons for hospital:

Type of Hospital : i.e. typeOfHospital : all values are null.
Verifier_Comment - sample jsons have this value. will add it.
Sub category of hospital- i.e. subCategory all values are null.
Availability - Will add this.
Type of bed available - Will add this.
How many beds available when you last checked : Will add this.

@divyagar @Deep-Codes can something be done for subCategory and typeOfHospital values as they are null for all records.

**Comment by karmakoder** [comment]
created https://github.com/coronasafe/life/pull/100
