### ISSUE TITLE
Rows added through form (crowdsource) to have a default 'Pending for verification' selected

### ISSUE THREAD

**Issue by chicksim** [coronasafe/life#44]
Rows added through form (data stream) will have a 'Pending for verification' default select under verification status column, such that we know that the following entries have been added through public form - crowdsource. And need to be approached differently

**Comment by chicksim** [comment]
Yes. it should be done on airtable @ProCode2

**Comment by chicksim** [comment]
![image](https://user-images.githubusercontent.com/83093301/115959699-1df98280-a52b-11eb-89a6-6e95199a7fa0.png)
This is how we get email alerts on covidfyi after every form is filled.

**Comment by bodhish** [comment]
closing artable issues
