### ISSUE TITLE
Prevent people from filling blank forms or miscreant forms (crowdsource)

### ISSUE THREAD

**Issue by chicksim** [coronasafe/life#45]
Cases

1. since no field is mandatory, ppl may go on filling blank forms. It will push more blank rows on that table. 
2. ppl may just write dfjkfhoaidfjoaifj 02348719-32478 on the fields and cause issue

can we prevent it at the form submission or before airtable entry or before frontend? such that either it doesn't get added to airtable at all, or at least doesn't show on the website.

**Comment by svadwlas** [comment]
@chicksim I was thinking of looking into this issue. 

But some of the links to the airtable forms are giving potential risk warning.
A plugin on my Chrome has designated it as malware.
![1](https://user-images.githubusercontent.com/29953654/115942722-9d2e7e00-a479-11eb-8227-0ccdd3720ae5.PNG)

**Comment by svadwlas** [comment]
Chrome (on my Android)  is blocking some of the links in our cards as potential malware

**Comment by bodhish** [comment]
You will need to enable validations on airtable. It's not an FE issue
