### ISSUE TITLE
layout break on small screen

### ISSUE THREAD

**Issue by Deep-Codes** [coronasafe/life#46]
Link: https://life.coronasafe.network/uttarakhand/dehradun/hospitals

<img width="542" alt="Screenshot 2021-04-24 at 4 32 18 AM" src="https://user-images.githubusercontent.com/61158210/115937745-33809500-a4b6-11eb-817e-e22c9a0802c3.png">

**Comment by divyagar** [comment]
Fixed https://github.com/coronasafe/life/commit/3397250a7f05086f3791603b75253f46e473ceb4
