### ISSUE TITLE
Automated Whatsapp Chats for Volunteers for verification

### ISSUE THREAD

**Issue by utsavshah1793** [coronasafe/life#47]
Created this friendly google-doc which volunteers can use
It will dynamically generate whatsapp-chat links and help them send messages at a very quick pace
https://docs.google.com/spreadsheets/d/1h1ZnRvnmbg8O1dUY-Wiv0EVbyo7IavCHOB89eZG73DE/edit#gid=0

**Comment by vjFaLk** [comment]
@karmakoder this isn't an issue per-se. Move it to where it has some visibility if this tool is useful?

**Comment by bodhish** [comment]
The process to get this WhatsApp bot running is super high. Let's not pursue this track now.
