### ISSUE TITLE
Automated commit messages from github actions should include date and time.

### ISSUE THREAD

**Issue by divyagar** [coronasafe/life#5]
I have tried `git commit -m "Some message $(date +'%d-%m-%y %T')"` and it fails for some reason, works on my machine.

**Comment by vandanabhandari** [comment]
Added https://github.com/coronasafe/life/pull/48 if you need this

**Comment by Deep-Codes** [comment]
@divyagar is this issue solved?

**Comment by vandanabhandari** [comment]
@divyagar On thinking further, you may not need this as you can see the date and time when a change is pushed when you do `git log`

**Comment by shrihari689** [comment]
Closing this as we are migrating from Airtable📍

**Comment by shrihari689** [comment]
Resolved as of 
https://github.com/coronasafe/life/commit/d45b2384ac8fe8ba57add89245969d5977f28c7f
📌
