### ISSUE TITLE
Need Formatting Fixes

### ISSUE THREAD

**Issue by hareshpatel1990** [coronasafe/life#51]
![image](https://user-images.githubusercontent.com/13939918/115948530-41e9a380-a4ec-11eb-893b-0eb6dbe20260.png)

**Comment by abhinandanarya06** [comment]
Hmm,
This was due to `phone` and `email` being `null`. UI still need some refactoring. Can you check it again? Any suggestion on how to show UI card are welcomed :)

**Comment by shrihari689** [comment]
Now everything is fine ✅
I hope we are always refactoring the card 🎨 in sync with data available. 📍 Soon it will be more responsive 📱

**Comment by hareshpatel1990** [comment]
@shrihari689 please check another formatting fixes @ [https://life.coronasafe.network/chhattisgarh/raigarh/medicine](https://life.coronasafe.network/chhattisgarh/raigarh/medicine)

![image](https://user-images.githubusercontent.com/13939918/116029926-04b21c80-a678-11eb-8016-54921b1864c5.png)
