### ISSUE TITLE
Dont show verified status for non verified request. 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#53]
Can we say `Checked on` instead of `verified`, for the yellow marked ones

![image](https://user-images.githubusercontent.com/14979190/115952053-a5320080-a501-11eb-9472-9542e197bfba.png)

**Comment by ProCode2** [comment]
@shrihari689 was this fixed?

**Comment by shrihari689** [comment]
No, I am doing it 📍 will finish and close 📌
