### ISSUE TITLE
Warning flag to remove in airtable form links on submit data link

### ISSUE THREAD

**Issue by chicksim** [coronasafe/life#57]
When i clicked on apply as a volunteer https://life.coronasafe.network/data it is again showing the warning flag error @bodhish 

Do we need to speak to airtable support again?

**Comment by ProCode2** [comment]
@bodhish reported this to airtable today.

**Comment by svadwlas** [comment]
Thanks @bodhish @chicksim. There are several campaigns here in the US wherein we are chipping in financial help to send Oxygen supplies/medical supplies etc. to India. Think we can integrate this somewhere on our APP, maybe as an FYI and then to streamline all info at one place?

**Comment by bodhish** [comment]
https://life.coronasafe.network/campaigns

**Comment by svadwlas** [comment]
Thanks @bodhish
