### ISSUE TITLE
Add a new page /campaigns 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/life#60]
Add a `/campaigns` page and add the following as 1st card. This is a simple change. Please ship out asap 

-----------------------------

As of today, India is undergoing a severe second wave with the world’s highest daily cases. Hospitals and healthcare providers are running out of resources in the fight against COVID-19 and the situation on the ground is dire. Oxygen is critically required to treat patients affected with COVID, many of whom require hospitalization due to fluctuating oxygen levels. However, there is a severe shortage of oxygen availability across hospitals in India. Oxygen concentrators are alternate devices to oxygen cylinders – while cylinders contain a finite amount of oxygen supply, a concentrator recycles oxygen from the air and delivers it to the patient. They can be used to manage patient requirements without looking for external sources of oxygen.

Swasth Digital Health Foundation (Swasth.app) along with ACT Grants is looking to procure oxygen concentrators and channel them to hospitals across levels of care in remote areas for COVID response and long-term health-system strengthening. These oxygen concentrators can save many thousands of lives and bolster much-needed resources for hospitals. They can also be used to treat outpatients, reducing the load on hospital beds and easing the stress faced by patients.
•	A high flow concentrator costs  Rs.85000 and treat up to 550 patients with a severe or critical illness.
•	A low flow concentrator costs Rs.45000 and can treat up to 900 patients with mild to moderate illness

Swasth is raising funds to support this effort. Please contribute by donating at: https://www.impactguru.com/fundraiser/oxygen 
The distribution and allocation of concentrators will be a transparent process with the method and impact metrics published openly so you can be assured of your contributions saving lives. 
If you are a company looking to deploy a CSR budget or an individual donor willing to contribute, please email us at shubha@swasthapp.com. We look forward to your support.

**Comment by Deep-Codes** [comment]
For `Partner With Us`: https://github.com/coronasafe/life/issues/39

**Comment by Deep-Codes** [comment]
Added via #66
