### ISSUE TITLE
Bug: Oxygen page show Medicine distribution list

### ISSUE THREAD

**Issue by hareshpatel1990** [coronasafe/life#63]
**Describe the bug**
Oxygen page show Remdesivir distribution list

**To Reproduce**
Go to [https://life.coronasafe.network/chhattisgarh/raipur/oxygen](https://life.coronasafe.network/chhattisgarh/raipur/oxygen)

**Expected behavior**
Need to display Oxygen Supplier contacts

**Screenshots**
![image](https://user-images.githubusercontent.com/13939918/115959903-31591d80-a52c-11eb-80de-0610ad94dc5b.png)

**Comment by ProCode2** [comment]
Checking

**Comment by ProCode2** [comment]
@hareshpatel1990 The bug doesn't show up in my case. Might be cache. Can you check again
![image](https://user-images.githubusercontent.com/50803990/115960140-43878b80-a52d-11eb-93f6-8ab06a4b880f.png)

**Comment by ProCode2** [comment]
Let me know if it persists

**Comment by hareshpatel1990** [comment]
okay
