### ISSUE TITLE
legend for verified / non-verified

### ISSUE THREAD

**Issue by Deep-Codes** [coronasafe/life#65]
**Is your feature request related to a problem? Please describe.**

Currently when a user visits: https://life.coronasafe.network/punjab/ludhiana/plasma
He/she sees the warning sign but might not understand the meaning of it.

**Describe the solution you'd like**
Adding a meaning of icons on top for reference.

**Describe alternatives you've considered**
using components something similar to GitHub badges (issues ones)

**Comment by rawris** [comment]
I can pick this one up, will add label with the icon.

**Comment by rawris** [comment]
I have created a generic badge component currently it supports verified and unverified but more configurations can be added by just updating an object.
PR: https://github.com/coronasafe/life/pull/70

**Comment by Deep-Codes** [comment]
Thanks, @rawris 🚀
