### ISSUE TITLE
consistent layout alignment

### ISSUE THREAD

**Issue by Deep-Codes** [coronasafe/life#69]
**Is your feature request related to a problem? Please describe.**
it's good to have consistent layout alignments

Compare: 

Center Aligned: 
https://life.coronasafe.network/delhi_(nct)/new_delhi/plasma

Left Aligned:
https://life.coronasafe.network/chhattisgarh

**Describe the solution you'd like**
To have Left Aligned those who are Center.

**Comment by rawris** [comment]
Also, one way can be by using a generic card component throughout all the listings so that the design can be consistent. I can try and pick it up tomorrow.

**Comment by Deep-Codes** [comment]
> Also, one way can be by using a generic card component throughout all the listings so that the design can be consistent. If no one picks it up tonight I can try and pick it up tomorrow.

Give it a Try!

**Comment by peeyush14goyal** [comment]
Will be covered in #72
