### ISSUE TITLE
Tailwind Classes are not working in production

### ISSUE THREAD

**Issue by ProCode2** [coronasafe/life#71]
**Describe the bug**
Tailwind classes are working fine in local builds and development. But they are not working when deployed in vercel. Adding the same as normal CSS works fine.

**To Reproduce**
1. Pull the [clipboard](https://github.com/coronasafe/life/tree/clipboard) branch.
2. In `AmbulanceCard.jsx` file, Add `ml-auto w-8` to this [className](https://github.com/coronasafe/life/blob/clipboard/components/AmbulanceCard.jsx#L24) attribute. and remove the style property.
3. Push to the same branch.
4. See the error in the deployment preview.

**Expected behavior**
The tailwind class name should work.

**Desktop (please complete the following information):**
- OS: MacOs
- Browser Brave browser
- Version 1.23.73

**Comment by shrihari689** [comment]
Looks working good! May I now what's not working 🤔

**Comment by ProCode2** [comment]
Fixed a few minutes back. It was some problem in tailwindcss config file.

**Comment by arnabsen1729** [comment]
Facing the same issue in https://github.com/coronasafe/life/pull/89, in the local environment, the CSS properties are loaded properly. The expected display is provided in the PR description. But the vercel preview, some of the styles are missing. Here is a comparison
| Local Environment | Vercel Build |
|---|---|
| ![image](https://user-images.githubusercontent.com/51032928/115998123-769c4e80-a603-11eb-9918-0d7e85e994de.png) | ![image](https://user-images.githubusercontent.com/51032928/115998115-67b59c00-a603-11eb-8d25-78ff4484e739.png) |

**Comment by shrihari689** [comment]
Not a right fix 🔨! But made some workaround https://github.com/coronasafe/life/pull/89#issuecomment-826355855

**Comment by ProCode2** [comment]
@shrihari689  Can close this?

**Comment by shrihari689** [comment]
Yeah done ‼ 🚀
