### ISSUE TITLE
create a card component

### ISSUE THREAD

**Issue by Deep-Codes** [coronasafe/life#72]
We need a Card Component instead of having 6 different ones.
Also a single alignment Left or center

**Comment by jenishjain** [comment]
can i pick this?

**Comment by shrihari689** [comment]
Sure @jenishjain  🚀 Pick it up 🔥🔥

**Comment by jenishjain** [comment]
> Sure @jenishjain 🚀 Pick it up 🔥🔥

working on it 🚀

**Comment by jenishjain** [comment]
seems like i need some access to raise PR to this project can you help ? @Deep-Codes

**Comment by Deep-Codes** [comment]
Sure thing

**Comment by Deep-Codes** [comment]
@jenishjain Awesome Work  🚀 .
