### ISSUE TITLE
issue while starting dev

### ISSUE THREAD

**Issue by sharunspi** [coronasafe/life#78]
```
> [PWA] Compile server
error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[2]!./styles/globals.css
TypeError: Object.entries(...).flatMap is not a function
    at Array.forEach (<anonymous>)
```
Showing this error while staring the development server . this may not be a bug but I am facing this when I start development server.

1. node 10.19.0
2. npm 7.11.1
3. OS : ubuntu

**Comment by Deep-Codes** [comment]
> ```
> > [PWA] Compile server
> error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[2]!./styles/globals.css
> TypeError: Object.entries(...).flatMap is not a function
>     at Array.forEach (<anonymous>)
> ```
> 
> Showing this error while staring the development server . this may not be a bug but I am facing this when I start development server.
> 
> 1. node 10.19.0
> 2. npm 7.11.1
> 3. OS : ubuntu

https://github.com/sharunspi/life.git

Wait I am cloning your repo let me see if I can reproduce.

**Comment by sharunspi** [comment]
This is the error code that i am getting
![Screenshot from 2021-04-25 14-56-04](https://user-images.githubusercontent.com/21285883/115988295-979a7a80-a5d6-11eb-9b0e-982bf15a9af0.png)

**Comment by bodhish** [comment]
Try this.

```
git pull
npm i
npm run dev
```

**Comment by sharunspi** [comment]
Issue solved by updating node to latest. node `10.19.0 --> 14`
need to add that in `package.json`
```
{
  "engines": {
    "node": ">=12.x"
  }
}
```
