### ISSUE TITLE
Add additional tab for real-time vaccine availability

### ISSUE THREAD

**Issue by avi-jain** [coronasafe/life#88]
**Is your feature request related to a problem? Please describe.**
With the vaccine shortage, and the flood gates opening on 1st May, it would be useful for the public to have data regarding the availability of vaccines (and type) at a centre. Right now people have to physically visit the centre(s) only to find that the vaccine is out of stock

**Describe the solution you'd like**
A tab for real-time vaccine availability updates provided through crowd-sourced as well as verified data

**Describe alternatives you've considered**
The BMC sheets (outdated info)

**Additional context**
Stemming off this https://twitter.com/mybmc/status/1386169619350654976

I'm willing to volunteer to pick this/anything else up :)

**Comment by Deep-Codes** [comment]
> **Is your feature request related to a problem? Please describe.**
> With the vaccine shortage, and the flood gates opening on 1st May, it would be useful for the public to have data regarding the availability of vaccines (and type) at a centre. Right now people have to physically visit the centre(s) only to find that the vaccine is out of stock
> 
> **Describe the solution you'd like**
> A tab for real-time vaccine availability updates provided through crowd-sourced as well as verified data
> 
> **Describe alternatives you've considered**
> The BMC sheets (outdated info)
> 
> **Additional context**
> Stemming off this https://twitter.com/mybmc/status/1386169619350654976
> 
> I'm willing to volunteer to pick this/anything else up :)

That is so awesome!

Please let me know what kind of Help you want.

**Comment by avi-jain** [comment]
Alright, so I haven't dealt with React in years (5 I think :P) but the codebase looks nice and easily extensible. Here are a few steps I can think of - 

- [x] Add vaccine tab to the pages
- [x] Add vaccine:false to your existing active_district_data.json for beta purposes
- [ ] Create new table in Airtable, create new column/s for vaccine wherever required and then change the scraper accordingly
- [ ] Create form for crowdsourcing availability information
- [ ] Additionally add checks to ensure duplicate entries aren't added (I think the forms are unstructured text fields as of now.)

I can raise a PR for the ticked ones first, if you can provide access to the tables (and let me know how to manipulate it without trouble) I can do that as well.

**Comment by bodhish** [comment]
@chicksim

**Comment by chicksim** [comment]
@avi-jain if I give you access, could you do it? I am busy with de-duplication efforts. and if you can build something that can identify duplicates, delete it from frontend and give it to us, we verify it and then put it back to the system. It will be great. can u make another issue for it! Please.

**Comment by avi-jain** [comment]
I can do the addition of a column in https://airtable.com/shrIlOoS6PyhIIVEv/tblvpmK21RJaGP07X/viwHyoxnIruo71pfW?blocks=bipKp2Nvee9X72oZp
cmmiw I think I'm late by 2 minutes because the scraper is scheduled to run at midnight so I don't think the column will show up instantly? 
As for the second thing, I'll create a new issue

**Comment by bodhish** [comment]
Scraper runs every one hour

**Comment by divyagar** [comment]
@avi-jain Can you add a new table vaccine in database. I'll change scraper and will add vaccine card in webste.

**Comment by bodhish** [comment]
I have created a new table https://airtable.com/invite/l?inviteId=invRACM91tD76GvSG&inviteToken=c6df2901ee26fe8534af6ca2200420f0c4f4a3b7090bdfb3d0119bc21bac2d12

**Comment by avi-jain** [comment]
Thanks! I'd made the code changes to a branch on the fork (https://github.com/avi-jain/life/tree/vaccine)
@bodhish I think you'd also have to add a column in the district data?

**Comment by chicksim** [comment]
Form view is also to be created with this and pushed on the liferesources.in/data so that ppl can fill in verified leads there

**Comment by divyagar** [comment]
@chicksim Please generate form link and send it here. I'll create form view.

**Comment by shrihari689** [comment]
Closing this as we moved out of Airtable 📍 and the Vaccine module is on live 🌴
