### ISSUE TITLE
build's css seems to be very bloated

### ISSUE THREAD

**Issue by Deep-Codes** [coronasafe/life#9]
Check the : [The Build CSS](https://life.coronasafe.network/_next/static/css/491fd2130f24e2c92500.css)

<img width="487" alt="Screenshot 2021-04-22 at 10 52 40 PM" src="https://user-images.githubusercontent.com/61158210/115759064-73b01c80-a3bd-11eb-85f0-b66687ca93fe.png">

**Comment by ProCode2** [comment]
Is this because of tailwind not purging unused CSS? @Deep-Codes 
```
warn - Tailwind is not purging unused styles because no template paths have been provided.
warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
```

**Comment by Deep-Codes** [comment]
<img width="711" alt="Screenshot 2021-04-23 at 5 33 35 AM" src="https://user-images.githubusercontent.com/61158210/115799142-762e6880-a3f5-11eb-80ca-133d9367995c.png">

🚀

**Comment by Deep-Codes** [comment]
But idk why it removes the Colors:


<img width="1033" alt="Screenshot 2021-04-23 at 5 55 09 AM" src="https://user-images.githubusercontent.com/61158210/115800580-88f66c80-a3f8-11eb-949f-1babf9868ff1.png">

**Comment by Deep-Codes** [comment]
Possible Reason:

<img width="872" alt="Screenshot 2021-04-23 at 6 42 12 AM" src="https://user-images.githubusercontent.com/61158210/115803687-0b822a80-a3ff-11eb-93e1-02fe2f4ebb4e.png">

https://tailwindcss.com/docs/optimizing-for-production

We have used this ->

https://github.com/coronasafe/life/blob/dacb9bdf9a0ac44b551ff224c610dccb84b356a2/components/TabLinks.js#L21

**Comment by Deep-Codes** [comment]
Got it Would Create a PR soon! ✅
