### ISSUE TITLE
Remove Plasma as a category

### ISSUE THREAD

**Issue by MadHatter92** [coronasafe/life#92]
Plasma doesn't work is the medical consensus among experts

**Comment by shrihari689** [comment]
Is this related to #86 ?
📍

**Comment by ProCode2** [comment]
@MadHatter92  just to clear, remove plasma as a category but keep showing the data? or remove it altogether?

**Comment by ProCode2** [comment]
> Is this related to #86 ?
> 📍

Oh looks like a duplicate

**Comment by shrihari689** [comment]
Maybe #86  would resolve this 📍

**Comment by MadHatter92** [comment]
my bad, please merge with older ticket
plasma should be gone gone from the website
