### ISSUE TITLE
Partners

### ISSUE THREAD

**Issue by Deep-Codes** [coronasafe/life#96]
## Partners

Crediting Initiatives who are lined up to Build One Initiatives.

- Add Your Logos

**Comment by chicksim** [comment]
http://www.covidindiacampaign.org/

**Comment by bodhish** [comment]
This will be an ever challenging list. Create a new page. Don't touch the current footer.

**Comment by Deep-Codes** [comment]
> This will be an ever challenging list. Create a new page. Don't touch the current footer.

Alright Makes sense.
